spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vpnoutline_db
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    open-in-view: false

    # validate db by model
    hibernate:
      ddl-auto: validate

  liquibase:
    changeLog: "classpath:db/vpn_script.sql"
    enabled: true